### PR TITLE
Dummy commit to trigger travis

### PR DESCRIPTION
**Pull request by zachmayer**
This just adds a couple silly tests that should kickoff a travis-ci job.

### CODE REVIEW

**Comment by zachmayer** [comment]
@terrytangyuan If you merge this PR, the travis/coveralls badges on your repo should light up!

**Comment by terrytangyuan** [comment]
Looks like the coveralls badge is not lighted up even though I've turned it on.

**Comment by zachmayer** [comment]
It might take a second to link through.  Try submitting another dummy commit in 10 mins if it's still not lit up

**Comment by terrytangyuan** [comment]
I guess something is not linked right. It's still not lit up after my several commits.

**Comment by zachmayer** [comment]
Look at the last few lines of your most recent build:
https://travis-ci.org/terrytangyuan/lfda

covr isn't installed.  That's my bad— I'll send you a pr to fix

**Pull request merged**
