### PR TITLE
Package setup

### PR DESCRIPTION
**Pull request by zachmayer**
devtools::check() passes

### CODE REVIEW

**Comment by zachmayer** [comment]
This does a lot of things:
- Standard packages setup
- MIT license
- testthat for testing
- travis ci for automated testing
- coveralls for test coverage reporting
- namespace cleanup 

You should be in the habit of running `devtools::check()` every time you make a change to this package, as that function will tell you if R CMD CHECK will pass for your package.

Also, I took the liberty of giving your package the [MIT license](https://en.wikipedia.org/wiki/MIT_License), but feel free to change it to anything else  you desire.   Here's a [list of licenses supported by CRAN](https://cran.r-project.org/web/licenses/), but don't feel limited to that list.

**Comment by terrytangyuan** [comment]
Thanks!

**Comment by zachmayer** [comment]
No problem!  Now you need to enable travis and coveralls for this repository.  Go to https://travis-ci.org and make an account.  Link it to your github account, and sync.   Then turn testing "on" for the lfda repository.

Do the same thing for coveralls.  Reply here if you have issues/questions

**Comment by terrytangyuan** [comment]
Okay! Both are turned on now.

**Pull request merged**
