### PR TITLE
Try to fix tests

### PR DESCRIPTION
**Pull request by zachmayer**

### CODE REVIEW

**Comment by zachmayer** [comment]
Don't try to merge this yes

**Comment by terrytangyuan** [comment]
Thanks. I am also trying to fix this by installing different set of packages as mentioned in this link: 
http://trestletech.com/2012/10/install-rgl-in-ubuntu/

**Comment by terrytangyuan** [comment]
BTW, mine didn't work. Don't try to pull it.

**Comment by zachmayer** [comment]
stop working for a sec so I can fix this PR

**Comment by zachmayer** [comment]
Ok, don't make any changes for a sec, and lets see what this build does

**Comment by zachmayer** [comment]
Ok, this one will pass on travis.  Once it does go ahead and merge, then finish writing tests!

**Comment by terrytangyuan** [comment]
Thanks so much! That's a lot of efforts!

**Comment by zachmayer** [comment]
These things are always trial and error.  Glad to help!

**Pull request merged**
