### PR TITLE
Fix R CMD CHECK false positive

### PR DESCRIPTION
**Pull request by zachmayer**

### CODE REVIEW

**Comment by terrytangyuan** [comment]
This did not pass. Would it matter?

**Comment by zachmayer** [comment]
The build right after you merged passed: https://travis-ci.org/terrytangyuan/lfda/builds/75009835

Sometimes, if you merge too quickly, travis can't find the old branch (because it gets deleted post-merge):

``` bash
$ git fetch origin +refs/pull/8/merge:
fatal: Couldn't find remote ref refs/pull/8/merge
The command "eval git fetch origin +refs/pull/8/merge:" failed. Retrying, 2 of 3.
```

Usually you wait for travis to pass before merging, but if travis passes post-merge, you're fine.  You can monitor travis builds here: https://travis-ci.org/terrytangyuan/lfda/builds

**Comment by terrytangyuan** [comment]
Got it. Thanks.

**Comment by zachmayer** [comment]
Also, here's the report on your latest build (that passed) on code coverage: https://coveralls.io/builds/3269167

`metric_transformed_data_viz_3d.R`, `helpers.R`m, and `lfda` all need more tests.

**Comment by terrytangyuan** [comment]
Got it. I was just about to push new commits for new tests. This is very helpful.

**Pull request merged**
